In [2]:
import yfinance as yf
yf.pdr_override()
import os

yfinance: pandas_datareader support is deprecated & semi-broken so will be removed in a future verison. Just use yfinance.

In [8]:
# get stock data
def get_stock_data(ticker, start_date, end_date):
    stock_data = yf.download(ticker, start=start_date, end=end_date)
    return stock_data

tickers = ['AAPL', 'MSFT', 'GOOGL', 'AMZN','600967.SS'] 
# tickers = ['600967.SS']
start_date = "2016-12-14"
end_date = "2018-06-08"
eval_start_date = "2018-06-11"
eval_end_date = "2018-08-30"
directory = 'StockData'
if not os.path.exists(directory): # create directory if it doesn't exist
    os.makedirs(directory)

for ticker in tickers:
    data = get_stock_data(ticker, start_date, end_date)
    data.to_csv(f'{directory}/{ticker}.csv') # save data to csv file
    eval_data = get_stock_data(ticker, eval_start_date, eval_end_date)
    eval_data.to_csv(f'{directory}/{ticker}_eval.csv') # save evaluation data to csv file

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

In [5]:
get_stock_data('600967.SS', start_date, end_date)

[*********************100%%**********************]  1 of 1 completed

             Open   High    Low  Close  Adj Close     Volume
Date
2021-01-04  12.43  12.75  11.91  12.50  11.870393  139747318
2021-01-05  12.31  12.81  12.09  12.25  11.632984   93102277
2021-01-06  12.11  12.68  12.05  12.50  11.870393   88806770
2021-01-07  12.36  12.55  12.15  12.36  11.737445   68598158
2021-01-08  12.23  12.48  11.89  12.14  11.528525   57781418
...           ...    ...    ...    ...        ...        ...
2023-09-22   8.89   9.02   8.88   9.01   9.010000    4762389
2023-09-25   9.01   9.01   8.87   8.89   8.890000    5742204
2023-09-26   8.90   8.93   8.80   8.81   8.810000    6244379
2023-09-27   8.79   8.86   8.79   8.83   8.830000    5682121
2023-09-28   8.85   8.90   8.83   8.86   8.860000    4788651

[667 rows x 6 columns]